---
# author: Levi

- name: copy cmm.tar
  unarchive:
    src: "{{ Path.Pkg_Src }}{{ Version.CMM_V }}.tar.gz"
    dest: "{{ Path.Pkg_Dst }}"

- name: install cmm
  shell: >
    source /etc/profile ~/.bash_profile;./install.sh
  args:
    chdir: "{{ Path.Pkg_Dst }}{{ Version.CMM_V }}"

- name: copy my.cnf
  copy:
    src: my.cnf
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'

- name: postinstall cmm
  shell: >
    source /etc/profile ~/.bash_profile;./postinstall.sh -x
  args:
    chdir: "{{ Path.Pkg_Dst }}{{ Version.CMM_V }}"
