---
# author: Levi

- name: judge if 3RD installed
  shell: ls /opt/fonsview/bin/version
  ignore_errors: True
  register: result

- name: copy 3rd.tar
  unarchive:
    src: "{{ Path.Pkg_Src }}{{ Version.fonsview_3RD_V }}.tar.gz"
    dest: "{{ Path.Pkg_Dst }}"

- name: install 3RD
  shell: source /etc/profile ~/.bash_profile;./install.sh
  args:
    chdir: "{{ Path.Pkg_Dst }}{{ Version.fonsview_3RD_V }}"
  when: result is failed
